#!/usr/bin/env bash

tmppwd=`pwd`

if [[ -L $0 ]]
then
    cd $(dirname $(readlink $0))
else
    cd $(dirname $0)
fi

cv_command(){
  local arg_name=$1 
  shift  
  ./libexec/cv-$arg_name "$@"
}

if [[ $# == 0 ]]
then
    cv_command usage  | less 
    exit 1
fi


var=$1
if [[ !  -f "./libexec/cv-$var" ]]
then
    cv_command usage  | less
    exit 1
fi

cv_command  "$@"

cd $tmppwd
