#!/usr/bin/env bash

tmppwd=`pwd`

if [[ -L $0 ]]
then
    cd $(dirname $(readlink $0))
else
    cd $(dirname $0)
fi

if [ !  -f /opt/cv/vcell.cfg ] && [ ! -f vcell.cfg ]
then
    echo "/opt/cv/vcell.cfg is not exists!"
    exit 1
fi
dos2unix /opt/cv/vcell.cfg >& /dev/null


cv_command(){
  local arg_name=$1 
  shift  
  ./libexec/cv-$arg_name "$@"
}

if [[ $# == 0 ]]
then
    cv_command usage  | less 
    exit 1
fi


var=$1
if [[ !  -f "./libexec/cv-$var" ]]
then
    cv_command usage  | less
    exit 1
fi

cv_command  "$@"

cd $tmppwd
