#!/usr/bin/env bash
#set -x
tmppwd=`pwd`
programname="$0"
while [[ -L $programname ]]
do
    cd `dirname $programname`
    name=$programname
    programname=$(readlink $name)
done
cd $(dirname $programname)

if [ !  -f /opt/cv/vcell.cfg ] && [ ! -f ../vcell.cfg ]
then
    echo "/opt/cv/vcell.cfg is not exists!"
    exit 1
fi
dos2unix /opt/cv/vcell.cfg >& /dev/null


cv_command(){
  local arg_name=$1 
  shift  
  ./cv-$arg_name "$@"
}

if [[ $# == 0 ]]
then
    cv_command usage  | less 
    exit 1
fi


var=$1
if [[ !  -f "./cv-$var" ]]
then
    cv_command usage  | less
    exit 1
fi

cv_command  "$@"

cd $tmppwd
