#!/usr/bin/env bash
# 
# Summary: 
# 
# Usage: cv  delete cvm 
#   

cd `dirname $0`


cv_delete_cvm(){
    xm destroy cvm-vm
    sleep 3
    xm delete cvm-vm >& /dev/null
}

arg=$1

case $arg in 
    cvm)
        cv_delete_cvm 
     ;;
     *)
     echo "
Usage: cv  delete cvm 
     "
     ;;
esac
