#!/usr/bin/env bash
# 
# Summary: configure vcell or cvm 
# 
# Usage: cv  setup [vcell | cvm ] 
#   
#       Option:
#        vcell  :        configure host/network/zk/ntp/service for vcell 
#        cvm    :        configure network/zk/storage/service for cvm
#
cd `dirname $0`

#source ../vcell.cfg
#source ./function

cv_setup_vcell () {
  ./cv-setup-vcell  
}

cv_setup_cvm(){
  ./cv-setup-cvm
}

arg=$1

case $arg in 
    cvm)
     cv_setup_cvm 
    ;;
    vcell)
     cv_setup_vcell
     ;;
     *)
     echo "
Usage: cv  setup [vcell | cvm ] 
     
    Option:
          vcell  :        configure host/network/zk/ntp/service for vcell 
          cvm    :        configure network/zk/storage/service for cvm
          "
     ;;
esac


