#!/usr/bin/env bash
# 
# Summary: configure vcell or cvm 
# 
# Usage: cv  setup [vcell | cvm ] 
#   
#       Option:
#        vcell  :        configure host/network/zk/ntp/service for vcell 
#        cvm    :        configure network/zk/storage/service for cvm
#
cd `dirname $0`

source ../vcell.cfg
source ./function

cv_setup_vcell () {
  cv_log "configure host"
  cv host    
  cv service host-agent restart
  cv_log "configure network"
  cv network 
  cv_log "configure zk"
  cv zk 
  cv service zkclient restart
  cv_log "configure sync ntp"
  cv ntp
  cv service cron restart
  cv_log "restart devagentd"
  cv service devagentd restart
  sleep 3
  cv_log "check all service"
  cv service 
}
cv_setup_cvm(){
  ./cv-setup-cvm
}

arg=$1

case $arg in 
    cvm)
     cv_setup_cvm 
    ;;
    vcell)
     cv_setup_vcell
     ;;
     *)
     echo "
Usage: cv  setup [vcell | cvm ] 
     
    Option:
          vcell  :        configure host/network/zk/ntp/service for vcell 
          cvm    :        configure network/zk/storage/service for cvm
          "
     ;;
esac


