#!/usr/bin/env bash -x 


cv_check_ip(){
    echo $1|grep "^[0-9]\{1,3\}\.\([0-9]\{1,3\}\.\)\{2\}[0-9]\{1,3\}$" > /dev/null;
    #IP地址必须为全数字 
    if [ $? -ne 0 ]
    then
        return 1
    fi
    ipaddr=$1
    a=`echo $ipaddr|awk -F . '{print $1}'`  #以"."分隔，取出每个列的值 
    b=`echo $ipaddr|awk -F . '{print $2}'`
    c=`echo $ipaddr|awk -F . '{print $3}'`
    d=`echo $ipaddr|awk -F . '{print $4}'`
    for num in $a $b $c $d
    do
        if [ $num -gt 255 ] || [ $num -lt 0 ]    #每个数值必须在0-255之间 
        then
            return 1
        fi
    done
    return 0
}

cv_check_single_zkip(){
    local zksingleip=$1
    local ipaddr=`echo $zksingleip | awk -F: '{print \$1}'`
    local port=`echo $zksingleip | awk -F: '{print \$2}'`
    local ret=0
    cv_check_ip $ipaddr
    if [ $? -ne 0 ]
    then
        echo "ip($ipaddr) is not valid"
        ((ret++))
    fi
    if [[ X"$port" != X"2181" ]]
    then
        echo "port($port) should be 2181"
        ((ret++))
    fi
    return $ret
}

cv_check_zkip(){
    local zkipaddr=$1
    local ret=0
    OLDIFS=$IFS
    IFS=,
    declare -a zklist=$(echo $zkipaddr) 
    IFS=$OLDIFS
    for i in $zklist
    do
        cv_check_single_zkip  $i
        if [ $? -ne 0 ]
        then
            ((ret++))
        fi
    done
    return $ret
}  
cv_check_vlan_not_repeat(){
    local ret=0
    declare -a arr=($1 $2 $3 $4)
    INDEX=4
    for((i=0;i < INDEX; i++))
    do
        for ((j=i+1; j < INDEX ; j++ ))
        do
#            echo i:$i j:$j
            a=${arr[$i]}
            b=${arr[$j]}
            if [ $a -eq $b ]
            then
                ((ret++)) 
                break 2
            fi
        done
    done
    return $ret
}

cv_log(){
    echo "[INFO]" "$@"
}
